services:
  php-app:
    build: . 
    container_name: pont-connect-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html  
    depends_on:
      - db-web
    networks:
      - pnt-connect-network

  db-web:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pontconnecte
      MYSQL_USER: Etudiant
      MYSQL_PASSWORD: P@ssword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d 
    networks:
      - pnt-connect-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    depends_on:
      - db-web
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-web
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - pnt-connect-network

volumes:
  db_data:

networks:
  pnt-connect-network:
    external: true